### PR TITLE
Added support for DEFAULT_AUTO_FIELD

### PR DESCRIPTION
**Pull request by 5parkp1ug**
# Context
Django earlier used to create id field using `django.db.fields.AutoField` which got replaced with `django.db.fields.BigAutoField`. So, when we run `makemigrations` command a new migration file is created for the django-recurrence app with the changes to id field. This migration should be shipped by default with the package.

Also, when the missing migration is created in a docker environment, permission issues are raised. This happens when pip install is done as root user and later a non-root user runs the application. Below is the snippet from the dockerfile which causes the issue - 

```
FROM python:3.9.10-slim

SHELL ["/bin/bash", "-c"]
RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
WORKDIR /home/user

# Install system dependencies
RUN apt-get update \
    && apt install -y libpq-dev gcc git

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ARG BUILD_ENVIRONMENT=local

# Install app dependencies
COPY ./requirements/ /home/user/requirements
RUN pip install -r ./requirements/$BUILD_ENVIRONMENT.txt

USER user
```

When migration is run using the above docker configuration the user `user` does not have privileges to create new migration file as the environment is owned by the root user.

# Changes
Added the new migration file.

### CODE REVIEW

**Comment by 5parkp1ug** [comment]
Can anyone merge this PR? Or else update if there are any suggestions?

**Comment by lino** [comment]
Thank you for your contribution. Will make sure that we'll release a new version ASAP.

**Comment by SriramPatibanda** [comment]
> Thank you for your contribution. Will make sure that we'll release a new version ASAP.

Any updates on when this can be released?

**Comment by lino** [comment]
Oh, I'm sorry, I'll block a timeslot in my calendar to push forward on this.

**Comment by lino** [comment]
Release v1.12 is on its way.

**Pull request merged**
